
.pf-hls-common:
  variables:
    VIVADO_HLS_LOG_ID: $${PF_ALGO_TAG}
    VIVADO_HLS_TCL_SCRIPT: run_hls_$${PF_ALGO_TAG}.tcl
    WORKDIR: pf
  parallel:
    matrix:
      - PF_ALGO_TAG: pfalgo3
        pfReg: Barrel
      - PF_ALGO_TAG: pfalgo2hgc
        pfReg: HGCal


pf:csim:
  extends:
    - .vivado_hls_csim
    - .pf-hls-common
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: none


pf:csynth:
  extends:
    - .vivado_hls_csynth
    - .pf-hls-common
  variables:
    pfBoard: VCU118
