include:
  - local: 'pf/gitlab-ci.yml'
  - local: 'puppi/gitlab-ci.yml'
  - local: 'l1-regionizer/multififo/gitlab-ci.yml'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^test/
    

stages:
  - pre-build
  - pre-build2
  - build
  - test
  - deploy
