
hls-csim:l1r-multififo:
  extends: .vivado_hls_csim
  variables:
    pfBoard: none
    pfReg: HGCal
    VIVADO_HLS_TCL_SCRIPT: run_hls_csim.tcl
    WORKDIR: l1-regionizer/multififo
  parallel:
    matrix:
      - regionizerMode: mux
        VIVADO_HLS_LOG_ID: l1r-mf-mux-csim
      - regionizerMode: nomux
        VIVADO_HLS_LOG_ID: l1r-mf-nomux-csim
      - regionizerMode: stream
        VIVADO_HLS_LOG_ID: l1r-mf-stream-csim


hls-csim:l1r-multififo-tm18:
  extends: .vivado_hls_csim
  variables:
    pfReg: HGCal
    pfBoard: VCU118
    VIVADO_HLS_TCL_SCRIPT: run_hls_csim_pf_puppi_tm18.tcl
    VIVADO_HLS_LOG_ID: l1r-mf-tm18-csim
    WORKDIR: l1-regionizer/multififo



# NOTE: Config for hdl-sim jobs still needs to be cleaned up to use standard template
#       (like the rest of the commands), once scripts refactorised to ensure same set
#       of commands are run for each job, specialised by setting values of variables
#       (where variables could also be used to set command line args).

.l1reg-multififo-vhdl-common:
  extends: .vivado_base
  stage: pre-build2
  variables:
    pfBoard: none
    pfReg: HGCal
    WORKDIR: l1-regionizer/multififo/vhdl/firmware/testbench

hdl-sim:l1r-multififo-mux:
  extends: .l1reg-multififo-vhdl-common
  variables:
    regionizerMode: mux
  dependencies:
    - 'hls-csim:l1r-multififo: [mux, l1r-mf-mux-csim]'
  script:
    - export PATH=${CI_PROJECT_DIR}/utils:${PATH}
    - "./run_vhdltb.sh vhdl-mux-tk  && pattern_diff.py vhdl-mux-tk_xsim.dir/output-{ref-tk,tk-vhdl_tb}.txt -s 54 --sr 54 -l 8 exact"
    - "./run_vhdltb.sh vhdl-mux-all && pattern_diff.py vhdl-mux-all_xsim.dir/output-{ref-emp,emp-vhdl_tb}.txt --emp -l 11 exact"

hdl-sim:l1r-multififo-nomux:
  extends: .l1reg-multififo-vhdl-common
  variables:
    regionizerMode: nomux
  dependencies:
    - 'hls-csim:l1r-multififo: [nomux, l1r-mf-nomux-csim]'
  script:
    - export PATH=${CI_PROJECT_DIR}/utils:${PATH}
    - "./run_vhdltb.sh vhdl-nomux-tk && pattern_diff.py vhdl-nomux-tk_xsim.dir/output-{ref-tk,tk-vhdl_tb}.txt -l 6 exact"
    - "./run_vhdltb.sh vhdl-nomux-calo && pattern_diff.py vhdl-nomux-calo_xsim.dir/output-{ref-calo,calo-vhdl_tb}.txt -l 7 exact"
    - "./run_vhdltb.sh vhdl-nomux-mu && pattern_diff.py vhdl-nomux-mu_xsim.dir/output-{ref-mu,mu-vhdl_tb}.txt -l 5 exact"

hdl-sim:l1r-multififo-stream:
  extends: .l1reg-multififo-vhdl-common
  variables:
    regionizerMode: stream
  dependencies:
    - 'hls-csim:l1r-multififo: [stream, l1r-mf-stream-csim]'
  script:
    - export PATH=${CI_PROJECT_DIR}/utils:${PATH}
    - "./run_vhdltb.sh vhdl-stream-tk  && pattern_diff.py vhdl-stream-tk_xsim.dir/output-{ref-tk,tk-vhdl_tb}.txt -c 1-25 -l 10 exact"
    - "./run_vhdltb.sh vhdl-stream-all && pattern_diff.py vhdl-stream-all_xsim.dir/output-{ref-emp,emp-vhdl_tb}.txt --emp -l 11 exact"
