
.linpuppi-hls-common:
  variables:
    VIVADO_HLS_LOG_ID: linpuppi-$${puppiReg}
    WORKDIR: puppi
  parallel:
    matrix:
      - puppiReg: [Barrel, HGCal]
        VIVADO_HLS_TCL_SCRIPT: run_hls_linpuppi_tracker.tcl
      - puppiReg: [HGCalNoTK, HF]
        VIVADO_HLS_TCL_SCRIPT: run_hls_linpuppi_forward.tcl


hls-csim:puppi:
  extends:
    - .vivado_hls_csim
    - .linpuppi-hls-common
  variables:
    puppiBoard: none


hls-csynth:puppi:
  extends:
    - .vivado_hls_csynth
    - .linpuppi-hls-common
  variables:
    puppiBoard: VCU118




.puppiSort-hls-common:
  variables:
    puppiReg: HGCal
    VIVADO_HLS_LOG_ID: puppiSort-hybrid-HGCal
    VIVADO_HLS_TCL_SCRIPT: run_hls_puppi_sort.tcl
    WORKDIR: puppi


hls-csim:puppiSort:
  extends:
    - .vivado_hls_csim
    - .puppiSort-hls-common


hls-csynth:puppiSort:
  extends:
    - .vivado_hls_csynth
    - .puppiSort-hls-common
  variables:
    sortAlgo: hybrid
